# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tunnel/v1/tunnel.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'tunnel/v1/tunnel.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16tunnel/v1/tunnel.proto\x12\ttunnel.v1\"#\n\rTunnelRequest\x12\x12\n\x04\x64\x61ta\x18\x01 \x01(\x0cR\x04\x64\x61ta\"$\n\x0eTunnelResponse\x12\x12\n\x04\x64\x61ta\x18\x01 \x01(\x0cR\x04\x64\x61ta2T\n\rTunnelService\x12\x43\n\x06Tunnel\x12\x18.tunnel.v1.TunnelRequest\x1a\x19.tunnel.v1.TunnelResponse\"\x00(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tunnel.v1.tunnel_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TUNNELREQUEST']._serialized_start=37
  _globals['_TUNNELREQUEST']._serialized_end=72
  _globals['_TUNNELRESPONSE']._serialized_start=74
  _globals['_TUNNELRESPONSE']._serialized_end=110
  _globals['_TUNNELSERVICE']._serialized_start=112
  _globals['_TUNNELSERVICE']._serialized_end=196
# @@protoc_insertion_point(module_scope)
