# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: product/v1/product.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'product/v1/product.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18product/v1/product.proto\x12\nproduct.v1\"#\n\x11GetProductRequest\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\"p\n\x12GetProductResponse\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n\x04name\x18\x02 \x01(\tR\x04name\x12 \n\x0b\x64\x65scription\x18\x03 \x01(\tR\x0b\x64\x65scription\x12\x14\n\x05price\x18\x04 \x01(\x02R\x05price2_\n\x0eProductService\x12M\n\nGetProduct\x12\x1d.product.v1.GetProductRequest\x1a\x1e.product.v1.GetProductResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'product.v1.product_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETPRODUCTREQUEST']._serialized_start=40
  _globals['_GETPRODUCTREQUEST']._serialized_end=75
  _globals['_GETPRODUCTRESPONSE']._serialized_start=77
  _globals['_GETPRODUCTRESPONSE']._serialized_end=189
  _globals['_PRODUCTSERVICE']._serialized_start=191
  _globals['_PRODUCTSERVICE']._serialized_end=286
# @@protoc_insertion_point(module_scope)
